/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author LIGIA
 */
import static java.sql.JDBCType.BLOB;
    import static java.sql.Types.BLOB;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import static org.hibernate.type.StandardBasicTypes.BLOB;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String area;
     private Date duracao;
     private String cadeira;
     private Blob videoaula;
     private Set estudantes = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int codigo, String nome, String area, Date duracao, String cadeira, Blob videoaula) {
        this.codigo = codigo;
        this.nome = nome;
        this.area = area;
        this.duracao = duracao;
        this.cadeira = cadeira;
        this.videoaula = videoaula;
    }
    public Curso(int codigo, String nome, String area, Date duracao, String cadeira, Blob videoaula, Set estudantes) {
       this.codigo = codigo;
       this.nome = nome;
       this.area = area;
       this.duracao = duracao;
       this.cadeira = cadeira;
       this.videoaula = videoaula;
       this.estudantes = estudantes;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Date getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(Date duracao) {
        this.duracao = duracao;
    }
    public String getCadeira() {
        return this.cadeira;
    }
    
    public void setCadeira(String cadeira) {
        this.cadeira = cadeira;
    }
    public Blob getVideoaula() {
        return this.videoaula;
    }
    
    public void setVideoaula(Blob videoaula) {
        this.videoaula = videoaula;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }

    public String getnome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public int getcodigo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getarea() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getduracao() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getcadeira() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public byte getvideoaula() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setcodigo(int aInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setnome(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setarea(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setduracao(java.sql.Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setcadeira(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setvideoaula(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

 @Override
    public String toString() {
        return "Curso [codigo=" + codigo + ", nome=" + nome
                + ", area=" + area + ", duracao=" + duracao + ", cadeira="
                + cadeira + "]";
    }   


}


