/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author LIGIA
 */
import java.util.Date;

/**
 * Estudante generated by hbm2java
 */
public class Estudante  implements java.io.Serializable {


     private int codigo;
     private teste.Curso curso;
     private String nome;
     private String apelido;
     private Date dataNasc;
     private String email;

    public Estudante() {
    }

    public Estudante(int codigo, teste.Curso curso, String nome, String apelido, Date dataNasc, String email) {
       this.codigo = codigo;
       this.curso = curso;
       this.nome = nome;
       this.apelido = apelido;
       this.dataNasc = dataNasc;
       this.email = email;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public teste.Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(teste.Curso curso) {
        this.curso = curso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


